#!/usr/bin/env bash
# Computes worktree-aware identity for mobile debug builds, mirroring the
# desktop dev experience in scripts/instance-env.sh: debug builds produced
# from a git worktree get a branch label in the app name and a unique app
# identifier so builds from multiple worktrees install side by side.
#
# In a worktree this writes two gitignored override files consumed by the
# native build systems (so direct Xcode / Android Studio / `flutter run`
# builds pick them up too):
#   mobile/ios/Flutter/WorktreeOverrides.xcconfig  (Debug builds only)
#   mobile/android/worktree.properties             (debug build type only)
# In the main checkout it removes any stale override files. Release and
# profile builds never read these overrides.
set -euo pipefail

# `just mobile-*` recipes unset these before invoking Flutter; do the same so
# an inherited GIT_DIR pointing elsewhere cannot misdetect the worktree.
unset GIT_DIR GIT_WORK_TREE

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ios_overrides="$repo_root/mobile/ios/Flutter/WorktreeOverrides.xcconfig"
android_props="$repo_root/mobile/android/worktree.properties"

# Worktree detection: in the main working tree --git-dir and --git-common-dir
# are identical; in any linked worktree they differ (same check as
# scripts/instance-env.sh).
in_worktree=0
if git -C "$repo_root" rev-parse --is-inside-work-tree &>/dev/null; then
    git_dir=$(git -C "$repo_root" rev-parse --git-dir)
    git_common_dir=$(git -C "$repo_root" rev-parse --git-common-dir 2>/dev/null)
    if [[ -n "$git_common_dir" && "$git_dir" != "$git_common_dir" ]]; then
        in_worktree=1
    fi
fi

if [[ "$in_worktree" != "1" ]]; then
    rm -f "$ios_overrides" "$android_props"
    exit 0
fi

branch=$(git -C "$repo_root" rev-parse --abbrev-ref HEAD)
label="${branch##*/}"

# iOS bundle-identifier slug: lowercase, non-alphanumerics collapsed to
# hyphens (hyphens are valid in bundle identifiers).
ios_slug=$(printf '%s' "$branch" | tr '[:upper:]' '[:lower:]' | sed -e 's/[^a-z0-9]/-/g' -e 's/--*/-/g' -e 's/^-//' -e 's/-$//')
[[ -n "$ios_slug" ]] || ios_slug="worktree"

# Android applicationId segments must match [a-z][a-z0-9_]*: swap hyphens for
# underscores and prefix a letter when the slug starts with a digit.
android_slug="${ios_slug//-/_}"
case "$android_slug" in
    [0-9]*) android_slug="w_$android_slug" ;;
esac

ios_bundle_id="com.buzz.buzzMobile.${ios_slug}"
android_suffix=".${android_slug}"

cat > "$ios_overrides" <<XCCONFIG
// Generated by scripts/mobile-worktree-env.sh — gitignored, do not edit.
// Applies to Debug builds only (included from Flutter/Debug.xcconfig).
BUNDLE_IDENTIFIER = ${ios_bundle_id}
APP_DISPLAY_NAME = Buzz (${label})
XCCONFIG

cat > "$android_props" <<PROPERTIES
# Generated by scripts/mobile-worktree-env.sh — gitignored, do not edit.
# Applies to the debug build type only (read by android/app/build.gradle.kts).
label=${label}
applicationIdSuffix=${android_suffix}
PROPERTIES

echo "📱 Worktree: ${label} (iOS ${ios_bundle_id}, Android xyz.block.buzz.mobile${android_suffix})"
